id: P6D8B16BF
initial_creation_type: input
source_metadata:
  title: Śāṅkhāyanagṛhyasūtra
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Veda -- Vedāṅga -- Gṛhyasūtra
  data entry: Muneo Tokunaga
  contribution to GRETIL: Muneo Tokunaga
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:50:28.545773'
last_modified_at: '2022-03-09T14:50:28.545785'
